/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function extract(html: string, options?: JsExtractOptions | undefined | null): JsExtractedContent

export declare function extractToMarkdown(html: string, options?: JsExtractOptions | undefined | null): string

export declare function htmlFragmentToMarkdown(html: string): string

export interface JsExtractedContent {
  title: string
  contentHtml: string
  textContent: string
  length: number
  score: number
  metadata: JsMetadata
}

export interface JsExtractOptions {
  minCandidateText?: number
  minOutputText?: number
  siblingScoreRatio?: number
  includeImages?: boolean
  mergePaginatedContent?: boolean
  maxPaginatedPages?: number
}

export interface JsMetadata {
  title?: string
  byline?: string
  excerpt?: string
  siteName?: string
  lang?: string
  publishedTime?: string
}
